// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: sqs.proto

package sqs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SQSReceiveMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VisibilityTimeout int64 `protobuf:"varint,1,opt,name=visibility_timeout,json=visibilityTimeout,proto3" json:"visibility_timeout,omitempty"`
	WaitTime          int64 `protobuf:"varint,2,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`
}

func (x *SQSReceiveMessageRequest) Reset() {
	*x = SQSReceiveMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQSReceiveMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQSReceiveMessageRequest) ProtoMessage() {}

func (x *SQSReceiveMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQSReceiveMessageRequest.ProtoReflect.Descriptor instead.
func (*SQSReceiveMessageRequest) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{0}
}

func (x *SQSReceiveMessageRequest) GetVisibilityTimeout() int64 {
	if x != nil {
		return x.VisibilityTimeout
	}
	return 0
}

func (x *SQSReceiveMessageRequest) GetWaitTime() int64 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

type SQSResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageID   string `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	MessageBody string `protobuf:"bytes,2,opt,name=messageBody,proto3" json:"messageBody,omitempty"`
}

func (x *SQSResponseMessage) Reset() {
	*x = SQSResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQSResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQSResponseMessage) ProtoMessage() {}

func (x *SQSResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQSResponseMessage.ProtoReflect.Descriptor instead.
func (*SQSResponseMessage) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{1}
}

func (x *SQSResponseMessage) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *SQSResponseMessage) GetMessageBody() string {
	if x != nil {
		return x.MessageBody
	}
	return ""
}

type SQSReceiveMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*SQSResponseMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *SQSReceiveMessageResponse) Reset() {
	*x = SQSReceiveMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQSReceiveMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQSReceiveMessageResponse) ProtoMessage() {}

func (x *SQSReceiveMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQSReceiveMessageResponse.ProtoReflect.Descriptor instead.
func (*SQSReceiveMessageResponse) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{2}
}

func (x *SQSReceiveMessageResponse) GetMessages() []*SQSResponseMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SQSDeleteMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageID string `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
}

func (x *SQSDeleteMessageRequest) Reset() {
	*x = SQSDeleteMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQSDeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQSDeleteMessageRequest) ProtoMessage() {}

func (x *SQSDeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQSDeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*SQSDeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{3}
}

func (x *SQSDeleteMessageRequest) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

type SQSDeleteMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDeleted bool `protobuf:"varint,1,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
}

func (x *SQSDeleteMessageResponse) Reset() {
	*x = SQSDeleteMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sqs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQSDeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQSDeleteMessageResponse) ProtoMessage() {}

func (x *SQSDeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sqs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQSDeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*SQSDeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_sqs_proto_rawDescGZIP(), []int{4}
}

func (x *SQSDeleteMessageResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

var File_sqs_proto protoreflect.FileDescriptor

var file_sqs_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x71, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x71, 0x73,
	0x1a, 0x0b, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a,
	0x18, 0x53, 0x51, 0x53, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x12, 0x76, 0x69, 0x73,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x76, 0x69, 0x73, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x69, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x77, 0x61, 0x69,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x12, 0x53, 0x51, 0x53, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x50, 0x0a, 0x19, 0x53,
	0x51, 0x53, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x71, 0x73,
	0x2e, 0x53, 0x51, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x37, 0x0a,
	0x17, 0x53, 0x51, 0x53, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x49, 0x44, 0x22, 0x38, 0x0a, 0x18, 0x53, 0x51, 0x53, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x32, 0xa4, 0x01, 0x0a, 0x0a, 0x53, 0x51, 0x53, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4f, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1d, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x53, 0x51, 0x53, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x53, 0x51, 0x53, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x45, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1c, 0x2e, 0x73, 0x71, 0x73, 0x2e, 0x53, 0x51, 0x53, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x73, 0x71, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sqs_proto_rawDescOnce sync.Once
	file_sqs_proto_rawDescData = file_sqs_proto_rawDesc
)

func file_sqs_proto_rawDescGZIP() []byte {
	file_sqs_proto_rawDescOnce.Do(func() {
		file_sqs_proto_rawDescData = protoimpl.X.CompressGZIP(file_sqs_proto_rawDescData)
	})
	return file_sqs_proto_rawDescData
}

var file_sqs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sqs_proto_goTypes = []interface{}{
	(*SQSReceiveMessageRequest)(nil),  // 0: sqs.SQSReceiveMessageRequest
	(*SQSResponseMessage)(nil),        // 1: sqs.SQSResponseMessage
	(*SQSReceiveMessageResponse)(nil), // 2: sqs.SQSReceiveMessageResponse
	(*SQSDeleteMessageRequest)(nil),   // 3: sqs.SQSDeleteMessageRequest
	(*SQSDeleteMessageResponse)(nil),  // 4: sqs.SQSDeleteMessageResponse
	(*emptypb.Empty)(nil),             // 5: google.protobuf.Empty
}
var file_sqs_proto_depIdxs = []int32{
	1, // 0: sqs.SQSReceiveMessageResponse.messages:type_name -> sqs.SQSResponseMessage
	0, // 1: sqs.SQSService.ReceiveMessage:input_type -> sqs.SQSReceiveMessageRequest
	3, // 2: sqs.SQSService.DeleteMessage:input_type -> sqs.SQSDeleteMessageRequest
	2, // 3: sqs.SQSService.ReceiveMessage:output_type -> sqs.SQSReceiveMessageResponse
	5, // 4: sqs.SQSService.DeleteMessage:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sqs_proto_init() }
func file_sqs_proto_init() {
	if File_sqs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sqs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQSReceiveMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sqs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQSResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sqs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQSReceiveMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sqs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQSDeleteMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sqs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQSDeleteMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sqs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sqs_proto_goTypes,
		DependencyIndexes: file_sqs_proto_depIdxs,
		MessageInfos:      file_sqs_proto_msgTypes,
	}.Build()
	File_sqs_proto = out.File
	file_sqs_proto_rawDesc = nil
	file_sqs_proto_goTypes = nil
	file_sqs_proto_depIdxs = nil
}
